name: Publish to npm

on:
  release:
    types: [published]   # run when a Release is published (not just created)
  workflow_dispatch:      # allow manual runs from the Actions tab
  # Optional: publish on tag push too (uncomment if you prefer tagging trigger)
  # push:
  #   tags:
  #     - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          scope: '@turbocat'   # optional but nice for scoped pkgs

      # Guard: ensure tag version == package.json version
      - name: Verify version matches tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          PKG=$(node -p "require('./package.json').version")
          echo "Tag: $TAG  package.json: $PKG"
          [ "$TAG" = "$PKG" ] || { echo "Version mismatch"; exit 1; }

      # Publish (public for scoped packages; safe to always include)
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
